name: Build PomodoroTimer Executable on Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # 允许创建 tag 和 release

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'version') ||
      contains(github.event.head_commit.message, 'Version')
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run build script
        run: python one_click_build.py

      - name: Rename dist folder to PomodoroTimer
        run: Rename-Item -Path dist -NewName PomodoroTimer

      - name: Compress PomodoroTimer folder
        run: Compress-Archive -Path PomodoroTimer\* -DestinationPath PomodoroTimer.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroTimer
          path: PomodoroTimer.zip

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: PomodoroTimer.zip
